### ISSUE TITLE
Feature request: Parse Info column into prometheus metrics 

### ISSUE THREAD

**Issue by ahakanbaba** [kumina/birdwatcher#1]
Consider birdcl output like this :

```
name    proto    table    state  since      info
 Mesh_10_101_4_182 BGP      master   up     2016-10-23  Established
   Description:    Connection to BGP peer
   Preference:     100
   Input filter:   ACCEPT
   Output filter:  calico_pools
   Routes:         1 imported, 1 exported, 1 preferred
   Route change stats:     received   rejected   filtered    ignored   accepted
     Import updates:              1          0          0          0          1
     Import withdraws:            0          0        ---          0          0
     Export updates:             44         25         18        ---          1
     Export withdraws:            0        ---        ---        ---          0
   BGP state:          Established

```

Would you consider adding a prometheus line to the output that represents the info. 

For example 
bird_info{bird_protocol_instance="Mesh_10_101_4_182",value=unknown} 0 
bird_info{bird_protocol_instance="Mesh_10_101_4_182",value=Active} 0
bird_info{bird_protocol_instance="Mesh_10_101_4_182",value=Established} 1

I am willing to write the implementation and add the tests. 
I wanted to reach out to you first whether you would welcome a PR ?

**Comment by EdSchouten** [comment]
That sounds like a good idea. Be sure to send a pull request!

If it's really a single state in which we're interested (Established), naming it `bird_info_established` and letting it a boolean would be sufficient. If we're interested in distinguishing between all states, your proposal looks fine as is.

**Comment by EdSchouten** [comment]
Done!
